"""Property-based tests for IR schema metamorphic properties.

This module tests universal properties about the IR schema structure that
should hold for all valid IR DataFrames, regardless of their content.

These are metamorphic properties - relationships between inputs and outputs
that hold without knowing exact values.
"""

import polars as pl
from hypothesis import given, settings

from fintran.core.schema import REQUIRED_FIELDS, validate_ir

from .conftest import valid_ir_dataframe


# Feature: core-infrastructure, Property 14: Schema Has Exactly Four Required Fields
@given(valid_ir_dataframe())
@settings(max_examples=100)
def test_schema_has_four_required_fields(df: pl.DataFrame) -> None:
    """Test that all valid IR DataFrames have exactly 4 required fields.

    **Validates: Requirements 18.1**

    Property: For any valid IR DataFrame, the number of required fields
    (date, account, amount, currency) should equal exactly 4.

    This is a metamorphic property that verifies the schema structure
    without depending on specific data values.

    Args:
        df: Random valid IR DataFrame generated by Hypothesis
    """
    # Validate the DataFrame first
    validated_df = validate_ir(df)

    # Count how many required fields are present
    required_fields_present = [field for field in REQUIRED_FIELDS if field in validated_df.columns]

    # Assert exactly 4 required fields
    assert len(required_fields_present) == 4, (
        f"Expected exactly 4 required fields, but found {len(required_fields_present)}: "
        f"{required_fields_present}"
    )

    # Also verify they are the expected fields
    assert set(required_fields_present) == set(REQUIRED_FIELDS), (
        f"Required fields mismatch. Expected {set(REQUIRED_FIELDS)}, "
        f"got {set(required_fields_present)}"
    )


# Feature: core-infrastructure, Property 15: Schema Has Between Four and Six Total Fields
@given(valid_ir_dataframe())
@settings(max_examples=100)
def test_schema_has_four_to_six_total_fields(df: pl.DataFrame) -> None:
    """Test that all valid IR DataFrames have between 4 and 6 total fields.

    **Validates: Requirements 18.2**

    Property: For any valid IR DataFrame, the total number of fields should be
    between 4 and 6 (4 required + 0-2 optional).

    This metamorphic property verifies that:
    - Minimum: All 4 required fields are present
    - Maximum: 4 required + 2 optional fields (description, reference)

    Args:
        df: Random valid IR DataFrame generated by Hypothesis
    """
    # Validate the DataFrame first
    validated_df = validate_ir(df)

    # Count total fields
    total_fields = len(validated_df.columns)

    # Assert between 4 and 6 fields
    assert 4 <= total_fields <= 6, (
        f"Expected between 4 and 6 total fields, but found {total_fields}: {validated_df.columns}"
    )


# Feature: core-infrastructure, Property 14 & 15: Combined Schema Structure
@given(valid_ir_dataframe())
@settings(max_examples=100)
def test_schema_structure_consistency(df: pl.DataFrame) -> None:
    """Test that schema structure is consistent across all valid IR DataFrames.

    **Validates: Requirements 18.1, 18.2, 18.3**

    Property: For any valid IR DataFrame:
    - Required fields = 4 (date, account, amount, currency)
    - Total fields = 4 to 6 (required + optional)
    - Optional fields = 0 to 2 (description, reference)

    This combined test verifies the complete schema structure invariant.

    Args:
        df: Random valid IR DataFrame generated by Hypothesis
    """
    # Validate the DataFrame first
    validated_df = validate_ir(df)

    # Get field counts
    total_fields = len(validated_df.columns)
    required_count = sum(1 for field in REQUIRED_FIELDS if field in validated_df.columns)
    optional_count = total_fields - required_count

    # Assert required fields count
    assert required_count == 4, f"Expected 4 required fields, got {required_count}"

    # Assert total fields range
    assert 4 <= total_fields <= 6, f"Expected 4-6 total fields, got {total_fields}"

    # Assert optional fields range
    assert 0 <= optional_count <= 2, f"Expected 0-2 optional fields, got {optional_count}"

    # Verify the relationship: total = required + optional
    assert total_fields == required_count + optional_count, (
        f"Field count mismatch: {total_fields} != {required_count} + {optional_count}"
    )
