"""Property-based tests for pipeline orchestration."""

from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any

import polars as pl
from hypothesis import given, settings

from fintran.core.pipeline import execute_pipeline

from .conftest import valid_ir_dataframe


class MockReader:
    """Mock Reader that returns a stored DataFrame."""

    def __init__(self, df: pl.DataFrame) -> None:
        """Initialize with a DataFrame to return.

        Args:
            df: DataFrame to return from read()
        """
        self.df = df

    def read(self, path: Path, **config: Any) -> pl.DataFrame:
        """Return the stored DataFrame.

        Args:
            path: Input path (ignored)
            **config: Configuration (ignored)

        Returns:
            The stored DataFrame
        """
        return self.df


class MockWriter:
    """Mock Writer that captures the written DataFrame."""

    def __init__(self) -> None:
        """Initialize with no captured DataFrame."""
        self.written_df: pl.DataFrame | None = None

    def write(self, df: pl.DataFrame, path: Path, **config: Any) -> None:
        """Capture the DataFrame being written.

        Args:
            df: DataFrame to write
            path: Output path (ignored)
            **config: Configuration (ignored)
        """
        self.written_df = df


# Feature: core-infrastructure, Property 11: Pipeline Identity Without Transforms
@given(valid_ir_dataframe())
@settings(max_examples=100)
def test_pipeline_identity_with_no_transforms(df: pl.DataFrame) -> None:
    """Test that pipeline without transforms preserves input DataFrame.

    Property: For any valid IR DataFrame, executing a pipeline with no transforms
    should produce output that equals the input (identity property).

    This validates:
    - Requirement 6.8: Pipeline with no transforms acts as identity function
    - Requirement 15.1: Property 11 - Pipeline identity without transforms
    - Requirement 15.2: Generate random valid IR DataFrames
    - Requirement 15.3: Assert output equals input using equals()

    Args:
        df: Random valid IR DataFrame generated by Hypothesis
    """
    # Create mock reader with the generated DataFrame
    reader = MockReader(df)

    # Create mock writer to capture output
    writer = MockWriter()

    # Use temporary files for paths (not actually used by mocks)
    with (
        NamedTemporaryFile(suffix=".csv") as input_file,
        NamedTemporaryFile(suffix=".parquet") as output_file,
    ):
        input_path = Path(input_file.name)
        output_path = Path(output_file.name)

        # Execute pipeline with no transforms
        execute_pipeline(
            reader=reader,
            writer=writer,
            input_path=input_path,
            output_path=output_path,
            transforms=[],
        )

    # Assert the written DataFrame equals the input DataFrame
    assert writer.written_df is not None, "Writer should have captured a DataFrame"
    assert df.equals(writer.written_df), (
        "Pipeline output should equal input when no transforms are applied"
    )
